name: Expressions and Context
on: [push, pull_request, issues, workflow_dispatch]

jobs:
  using-expressions-and-contexts:
    runs-on: ubuntu-latest
    steps:
      - name: Expressions
        id: expressions
        run: |
          echo ${{ 1 }}
          echo ${{ 1.0 }}
          echo ${{ 'string' }}
          echo ${{ 1 > 2 }}
          echo ${{ 'string' == 'string' }}
          echo ${{ true && false }}
          echo ${{ true || (false && true) }}
      - name: Dump Contexts
        run: |
          echo " ${{ toJson(github) }}"
          echo " ${{ toJson(job) }}"
          echo " ${{ toJson(runner) }}"
          echo " ${{ toJson(secrets) }}"
          echo " ${{ toJson(steps) }}"
          echo " ${{ toJson(needs) }}"
