---
name: test output
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run output script
        id: greet
        run: |
          chmod +x ./build/set_output.sh
          ./build/set_output.sh

      - name: Use output
        run: echo "Message was '${{ steps.greet.outputs.outout }}'"
